-- SCRIPT PARA LIMPIAR LA BASE DE DATOS
-- Borra todas las tablas del schema QUERY_MEVAJI y sus datos

USE [GD1C2026]
GO

-- Deshabilitar constraint checks temporalmente
ALTER TABLE QUERY_MEVAJI.Detalle_Venta_Excursion DROP CONSTRAINT IF EXISTS FK__Detalle_Venta_Excursion_Venta;
ALTER TABLE QUERY_MEVAJI.Detalle_Venta_Excursion DROP CONSTRAINT IF EXISTS FK__Detalle_Venta_Excursion_Excursion;
ALTER TABLE QUERY_MEVAJI.Detalle_Venta_Vuelo DROP CONSTRAINT IF EXISTS FK__Detalle_Venta_Vuelo_Venta;
ALTER TABLE QUERY_MEVAJI.Detalle_Venta_Vuelo DROP CONSTRAINT IF EXISTS FK__Detalle_Venta_Vuelo_Vuelo;
ALTER TABLE QUERY_MEVAJI.Detalle_Propuesta_Vuelo DROP CONSTRAINT IF EXISTS FK__Detalle_Propuesta_Vuelo_Propuesta;
ALTER TABLE QUERY_MEVAJI.Detalle_Propuesta_Vuelo DROP CONSTRAINT IF EXISTS FK__Detalle_Propuesta_Vuelo_Vuelo;
ALTER TABLE QUERY_MEVAJI.Detalle_Venta_Hospedaje DROP CONSTRAINT IF EXISTS FK__Detalle_Venta_Hospedaje_Venta;
ALTER TABLE QUERY_MEVAJI.Detalle_Venta_Hospedaje DROP CONSTRAINT IF EXISTS FK__Detalle_Venta_Hospedaje_Habitacion;
ALTER TABLE QUERY_MEVAJI.Detalle_Propuesta_Hospedaje DROP CONSTRAINT IF EXISTS FK__Detalle_Propuesta_Hospedaje_Propuesta;
ALTER TABLE QUERY_MEVAJI.Detalle_Propuesta_Hospedaje DROP CONSTRAINT IF EXISTS FK__Detalle_Propuesta_Hospedaje_Habitacion;
GO

-- ELIMINAR TABLAS EN ORDEN INVERSO DE DEPENDENCIAS
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Venta_Excursion;
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Venta_Vuelo;
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Propuesta_Vuelo;
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Venta_Hospedaje;
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Propuesta_Hospedaje;
DROP TABLE IF EXISTS QUERY_MEVAJI.Venta;
DROP TABLE IF EXISTS QUERY_MEVAJI.Propuesta;
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Solicitud;
DROP TABLE IF EXISTS QUERY_MEVAJI.Solicitud;
DROP TABLE IF EXISTS QUERY_MEVAJI.Habitacion;
DROP TABLE IF EXISTS QUERY_MEVAJI.Hospedaje;
DROP TABLE IF EXISTS QUERY_MEVAJI.Vuelo;
DROP TABLE IF EXISTS QUERY_MEVAJI.Aeropuerto;
DROP TABLE IF EXISTS QUERY_MEVAJI.Aerolinea;
DROP TABLE IF EXISTS QUERY_MEVAJI.Detalle_Encuesta;
DROP TABLE IF EXISTS QUERY_MEVAJI.Encuesta;
DROP TABLE IF EXISTS QUERY_MEVAJI.Cliente;
DROP TABLE IF EXISTS QUERY_MEVAJI.Agente;
DROP TABLE IF EXISTS QUERY_MEVAJI.Agencia;
DROP TABLE IF EXISTS QUERY_MEVAJI.Localidad;
DROP TABLE IF EXISTS QUERY_MEVAJI.Ciudad;
DROP TABLE IF EXISTS QUERY_MEVAJI.Provincia;
DROP TABLE IF EXISTS QUERY_MEVAJI.Excursion;
DROP TABLE IF EXISTS QUERY_MEVAJI.Estado_De_Propuesta;
DROP TABLE IF EXISTS QUERY_MEVAJI.Proveedor;
DROP TABLE IF EXISTS QUERY_MEVAJI.Alianza;
DROP TABLE IF EXISTS QUERY_MEVAJI.Aspecto;
DROP TABLE IF EXISTS QUERY_MEVAJI.Medio_De_Pago;
DROP TABLE IF EXISTS QUERY_MEVAJI.Canal_De_Venta;
DROP TABLE IF EXISTS QUERY_MEVAJI.Pais;

-- ELIMINAR PROCEDURES
--DROP PROCEDURE IF EXISTS QUERY_MEVAJI.cargar_paises;

-- ELIMINAR SCHEMA
--DROP SCHEMA IF EXISTS QUERY_MEVAJI;

PRINT 'Base de datos limpiada correctamente - Schema QUERY_MEVAJI eliminado';
GO
